CREATE TABLE IF NOT EXISTS `PRODUCTS`
(
    `id`         BINARY(16)     NOT NULL,
    `created_at` DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` BINARY(16)     NOT NULL,
    `updated_at` DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `version`    INTEGER        NOT NULL DEFAULT 0,
    `name`       VARCHAR(255)   NOT NULL,
    `sku`        VARCHAR(255)   NOT NULL,
    `price`      DECIMAL(12, 2) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;

CREATE UNIQUE INDEX `UK_PRODUCTS_SKU` ON `PRODUCTS` (`sku`);

CREATE INDEX `IDX_PRODUCTS_CREATED_AT` ON `PRODUCTS` (`created_at`);